Adding icons and autogeneration script
tracedata/design-system pull request #31
Opened 2020-10-30 18:44 UTC by mgiamberardino

2020-10-30 18:54 UTC, seb7887 approved these changes
LGTM :clap:

2020-11-02 21:11 UTC, ryanjwilke requested changes
Only one small change. Otherwise everything looks fine to me. If you're fine maintaining the icon system that you put forward here, then I'm good with that 👍

2020-11-02 21:11 UTC, ryanjwilke commented on css/tracedata.sass
> +@import "icons"
Only thing I'd say here is that the icons file should probably be imported below the reset (i.e. line 5) as this is more of a utility.

2020-11-03 20:59 UTC, ryanjwilke approved these changes

2020-11-10 14:02 UTC, merged