Create Table component using react-table
tracedata/design-system pull request #32
Opened 2020-11-11 19:51 UTC by mgiamberardino

2020-11-11 19:59 UTC, ryanjwilke commented on css/components/table.sass
> +        stroke: $text-200
You should theoretically be able to apply this directly to the `.icon` if that's the SVG. The goal here is typically to reduce specificity as much as possible as `.icon svg path` is a rather slow search for the browser to have to make.

2020-11-11 20:00 UTC, ryanjwilke commented on css/components/table.sass
> +@for $i from 1 through 10
💥 Nice ;)

2020-11-11 20:04 UTC, ryanjwilke requested changes
I like that you made these sortable already. Nice work!

I left a couple small comments on some improvements to be made to the CSS if possible.

2020-11-11 20:10 UTC, ryanjwilke commented on css/components/table.sass
> +        stroke: $text-200
One issue I'm noticing related to this. It would appear that our `Icon` component prints out an `i` tag, but ideally it could print out the SVG directly and just apply the `.icon` class directly to it.

2020-11-11 20:16 UTC, mgiamberardino commented on css/components/table.sass
> +        stroke: $text-200
I can add a classname prop to the icons to be able to do that.

2020-11-11 20:43 UTC, ryanjwilke commented on css/components/table.sass
> +        stroke: $text-200
Cool. It'd be best to fix that issue soon as icons get used kind of everywhere.

2020-11-12 14:44 UTC, seb7887 approved these changes
LGTM :clap:

2020-11-12 14:57 UTC, Gahen commented on pages/components/tables.tsx
>        <Code className={css.code}>
Can't you use `<code><pre>` instead of the `&nbsp;`?

2020-11-12 16:46 UTC, ryanjwilke commented on css/components/table.sass
> +    stroke: $text-200
You should be able to add this directly to the `.th-icon` class as long as you remove the `stroke="black"` from the SVG icon itself. Ideally, you don't want any inline colors inside those icons so you can easily override those colors in CSS. I tried this in the browser and it worked well.

2020-11-12 16:48 UTC, ryanjwilke commented on components/icons/generated/DownIcon.tsx
> +<path d="M4 9L8 13M8 13L12 9M8 13V3" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
It's attributes like `stroke="black"` that should get removed from these files. Same with any `fill="..."`. All those colors should be applied via CSS.

2020-11-12 17:13 UTC, ryanjwilke commented on pages/components/tables.tsx
>        <Code className={css.code}>
In theory, yeah. However, it can get a little messy getting those results to work as well. I believe we can do the same in CSS without needing the `pre` tag. Either way, both can be a little funky to work with in order to get the "tab" results you want.

2020-11-12 17:59 UTC, ryanjwilke commented on css/icons.sass
> +  stroke: $black-900
@mgiamberardino This may be fine for now, but we can't always be guaranteed that the icon will be a stroke :) Sometimes it will be a fill. I guess this should be overridable so maybe it's fine as long as doesn't put strokes on icons that don't need them.

2020-11-12 18:00 UTC, ryanjwilke approved these changes
Looks great. Nice work @mgiamberardino

2020-11-12 18:34 UTC, merged