Create Button component and icon component improvements
tracedata/design-system pull request #33
Opened 2020-11-13 18:24 UTC by seb7887

2020-11-13 19:44 UTC, ryanjwilke commented on css/components/button.sass
> +    display: flex;
@seb7887 The `;` character is invalid typically in Sass. Only `.scss` files need the `;` characters.

2020-11-13 19:46 UTC, ryanjwilke commented on css/components/button.sass
> +        svg
A couple things here. We should try to apply this directly to the `svg` via some kind of class on the SVG tag. `.btn-icon` as an example. Also, the `color` attribute is should typically be `fill` or `stroke` for most SVGs, unless the SVG is using something like `fill: currentColor`.

2020-11-13 19:49 UTC, ryanjwilke requested changes
Left a few comments on some small items I noticed. Looks like you added a lot in here. Thanks for doing that! 💥

2020-11-13 19:51 UTC, seb7887 commented on css/components/button.sass
> +        svg
I replaced stroke and fill values ​​to `currentColor`, that's why I used color here

2020-11-13 19:53 UTC, seb7887 commented on css/components/button.sass
> +    display: flex;
Thank you for noticing it. Will fix it

2020-11-16 14:30 UTC, mgiamberardino requested changes
LGTM, some minor changes. Also, I think you need to update the iconography.template to use double quotes and semicolons.

2020-11-16 14:30 UTC, mgiamberardino commented on components/button/button.tsx
> +type ButtonVariant = "contained" | "outlined" | "inline";
I would use "default" instead if "contained" here

2020-11-16 14:30 UTC, mgiamberardino commented on components/button/button.tsx
> +      "btn-xs": size === "xs",
Can we replace all "btn-{size}" for something like:
```
     [`btn-${size}`]: true,
```

And all "btn-{size}-rounded" with something like:
```
      [`btn-${size}-rounded`]: rounded,
```

Same can be applied for the "btn-{type}":
```
      [`btn-${type}`]: variant === "contained",
      [`btn-${type}-outlined`]: variant === "outlined",
      [`btn-${type}-inline`]: variant === "inline",
```

2020-11-16 16:36 UTC, ryanjwilke commented on css/components/button.sass
> +        svg
Ahh, makes sense.

The only thing we should aim for here then really is to find a way to apply this to the icon without needing to increase the specificity of the CSS (e.g. `.icon-name { ... }` over `.icon svg { ... }`). The former is always preferable as it makes it easier to overwrite should that need ever arise. It's also takes the browser more time to render the latter option as browsers read from right to left. It seems like a small issue, but they do add up quickly.

2020-11-16 16:38 UTC, ryanjwilke commented on components/button/button.tsx
> +      "btn-xs": size === "xs",
Good catch. Probably would shorten the code up a bit.

2020-11-16 16:58 UTC, mgiamberardino commented on css/components/button.sass
> +        svg
We have a way right now since all <svg..>s has the class `.icon`se we could do:
```
  &-icon
    &-outlined
      .icon
```

2020-11-17 01:21 UTC, mgiamberardino approved these changes
LGTM, but I would remove the .btn-{size}-icon class at all.

2020-11-17 01:21 UTC, mgiamberardino commented on css/components/button.sass
> +    &-icon
I think we should remove the intermmediate class: "btn-{size}-icon" and just do something like:
```
  &-sm
    .icon
      ...style
```

Since we are using a condition to add the size of the icon based on the amount of childrens and having a use case like:
```
<Button ...>
  <UpIcon ... />
  some <span className="some-class">strong text</span>
</Button>
```
should work and will have 3 children.
Or maybe just always add the: "btn-{size}-icon" class.

2020-11-24 17:00 UTC, ryanjwilke commented on css/components/button.sass
> +        margin-right: 8px;
@seb7887 Another semi-colon here that is essentially invalid in Sass files.

2020-11-24 17:01 UTC, ryanjwilke commented on css/icons.sass
> +  fill: currentColor;
Same here.

2020-11-24 17:01 UTC, ryanjwilke commented on css/icons.sass
> +  stroke: currentColor;
Same here.

2020-11-24 17:01 UTC, ryanjwilke commented on css/pages/components/buttons.module.sass
> +  flex-wrap: wrap;
Same here.

2020-11-24 17:01 UTC, ryanjwilke commented on css/pages/components/buttons.module.sass
> +    margin-bottom: 8px;
Same here.

2020-11-24 17:06 UTC, ryanjwilke commented on css/components/button.sass
> +      &:not(:last-child)
Although this is really convenient, this is typically preferable to avoid this kind of CSS. The `:not` selector is actually a pretty costly operation to run for browsers, so it can actually cause the page rendering times to be pretty slow.

As a quick example, a few years back I was working with some designers and engineers on a large-scale product and by removing selectors like this in our `Buttons.sass` file, the rendering time of the entire application improved by **more than 1 second**. We were pretty astonished by this. It's also a good reason to take more of a utility-based approach (e.g. Tachyons, Tailwind) as browsers render types of styles so much faster.

2020-11-24 17:07 UTC, ryanjwilke requested changes
Left a few more comments for you to consider. The syntax issues are the most critical. I'm kind of surprised the builds don't break as a result of those. I guess we could probably add some better CI checks in the future.

2020-12-09 17:32 UTC, ryanjwilke approved these changes
Looks good to me 👍

2020-12-10 14:07 UTC, merged