Code block component and solve package vulnerabilities
tracedata/design-system pull request #35
Opened 2020-11-25 16:39 UTC by seb7887

[ENG-1741](https://tracedata.atlassian.net/browse/ENG-1741)
[ENG-1843](https://tracedata.atlassian.net/browse/ENG-1843)

2020-12-03 14:12 UTC, mgiamberardino approved these changes
LGTM. Great work! The only comment I have is that we should not put all the libraries as peer dependencies.

2020-12-09 17:29 UTC, ryanjwilke requested changes
I left a few small comments to address regarding the CSS styles. Other than that, this is a really major improvement on the component that's currently there. Nice work!

2020-12-09 17:29 UTC, ryanjwilke commented on css/components/code.sass
> +    div
If possible, it'd be great to give this element a name (e.g. `&-container`). This makes it easier to find, and also makes the browser have to do less work to render the styles too.

2020-12-09 17:29 UTC, ryanjwilke commented on css/components/code.sass
> +      &.highlighted
This is a good example were we could extend from the parent classes name (e.g. `&-highlighted`). If we can avoid chaining of classes (i.e. `.one.two.three`), it's always a good practice to do avoid this. In practice, it's rare that we actually need to chain classes together. This seems like a scenario where we don't really need to either.

2020-12-09 17:29 UTC, ryanjwilke commented on css/components/code.sass
> +.focus
Is this a shared utility class across all components? It might be worth making this more specific if it only pertains to this one component. (e.g. `.code-focus { ... }`)

2020-12-09 17:29 UTC, ryanjwilke commented on css/components/code.sass
> +    textarea
If you can find a way to combine the two `textarea` styles together, that'd be ideal.

For example:
```
.code
  &-text
    cursor: default
    &-editable
      cursor: text
```

There's probably a better way to write that is `textarea` elements are likely to have `cursor: text` by default anyways so the style is likely redundant.

2020-12-16 17:02 UTC, ryanjwilke approved these changes
I think this is good for now. We can address the other comments that I had at a later stage in a Sass cleanup project. They're not critical.

2020-12-16 17:06 UTC, merged