Switch component
tracedata/design-system pull request #36
Opened 2020-11-30 17:07 UTC by seb7887

2020-12-02 00:06 UTC, mgiamberardino approved these changes
LGTM

2020-12-09 16:58 UTC, ryanjwilke requested changes
I left a few small suggestions for the CSS styles which would be nice to address. The design of the component looks good in the preview environment. Thanks for putting this together.

2020-12-09 16:58 UTC, ryanjwilke commented on components/switch/switch.tsx
> +      <span />
Can we give this span a class name so we can target it a little more efficiently in the CSS?

Example:
```Sass
.switch
  ...
  &-circle
    ...
    &-lg
       ...
```

2020-12-09 16:58 UTC, ryanjwilke commented on css/components/switch.sass
> +  span
Ideally, this would have its own class name so browsers render it a little quicker (see the comment above).

2020-12-09 16:58 UTC, ryanjwilke commented on css/components/switch.sass
> +    span
Whenever possible, it's preferable to have these types of styles closely grouped together.

For example:
```Sass
.switch-circle
  ...
  &-lg
    ...
  &-enabled
    ...
```

In this example, all styling for this element are grouped into a single location which makes it much easier to find and style. It's a good pattern to have, especially as components and styles increase in complexity.

2020-12-09 17:35 UTC, ryanjwilke approved these changes
🚀 Nice work!

2020-12-10 14:13 UTC, merged