Table improvements
tracedata/design-system pull request #37
Opened 2020-12-16 17:35 UTC by seb7887

2020-12-21 20:42 UTC, ryanjwilke commented on yarn.lock
> +<<<<<<< HEAD
@seb7887 We'll probably need to fix this before this merges.

2020-12-21 20:44 UTC, ryanjwilke commented on css/components/table.sass
>  .tr.expanded
@seb7887 Any chances we can turn the output of this into `.tr-expanded` instead of chaining classes together?

2020-12-21 20:46 UTC, ryanjwilke commented
@seb7887 Can we use the smaller chevron icon in the pagination prev/next buttons?

<img width="113" alt="Screen Shot 2020-12-21 at 21 45 35" src="https://user-images.githubusercontent.com/211597/102820711-fd32ec00-43d5-11eb-98f3-52af48964d2d.png">

You'll notice it's a bit different from what's in Figma.

2020-12-21 20:47 UTC, ryanjwilke requested changes
Left a feedback on a few small items. It's getting close though. Love all the progress on this. Great idea to build it directly into the table.

2020-12-22 13:49 UTC, mgiamberardino approved these changes
LGTM. Just some small comments that would be nice to have.

2020-12-22 13:49 UTC, mgiamberardino commented on package/src/pagination/pagination.tsx
> +  variant?: PaginationVariant;
We could use conditional types by using type unions:
```javascript
interface IntA {
  variant: "typeA";
  someMandatoryPropA: string;
}

interface IntB {
  variant: "typeB";
  someOtherProp?: string
}

export type IComponentProps = IntA | IntB;

...

export const Component: React.FunctionComponent<IComponentProps> = (props) => {

  if (props.variant === "typeA) {
    // here props is of type IntA
  } else {
    // here props is of type IntB
  }
}
```

2020-12-22 13:49 UTC, mgiamberardino commented on package/src/table/table.tsx
> +  const memoizedSortBy = useMemo(() => initialSortBy, [initialSortBy]);
If initialSortBy props is not memoized in the component is passing this prop then this useMemo will behave as this property is not memoized since you are using the value itself as dependency. I think you can remove this line and we should ask to the user of this component to memoize the initialSortBy on the component using it.

2021-01-07 19:12 UTC, ryanjwilke approved these changes
Looks great. Thanks for cleaning all this up @seb7887

2021-01-07 19:24 UTC, merged