Tab Improvements
tracedata/design-system pull request #56
Opened 2021-02-04 23:27 UTC by ryanjwilke

2021-02-05 19:40 UTC, ryanjwilke commented on package/src/tabs/tabs.tsx
> -      <div className="active-tab">
@mgiamberardino I couldn't quite figure out what this `.active-tab` was for. Is that where you're dropping content once you've clicked on a certain tab?

2021-02-08 13:52 UTC, mgiamberardino requested changes
LGTM. Just one comment to avoid extra re-renders.

2021-02-08 13:52 UTC, mgiamberardino commented on package/src/tabs/tabs.tsx
> +  const containerClasses = classnames('tab-container', `tab-container-${type}`, classNames);
Why removing the `useMemo` here? We should use hooks to keep states inside the components.

2021-02-08 18:22 UTC, ryanjwilke commented on package/src/tabs/tabs.tsx
> +  const containerClasses = classnames('tab-container', `tab-container-${type}`, classNames);
That should be fixed now.

2021-02-08 18:22 UTC, ryanjwilke commented on package/src/tabs/tabs.tsx
> +          const linkClasses = classnames({
@mgiamberardino Would you use the `useMemo` function here as well?

2021-02-08 19:53 UTC, mgiamberardino approved these changes
LGTM

2021-02-08 20:16 UTC, merged